# Generated by Django 2.2.4 on 2019-08-21 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViberUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viber_id', models.CharField(blank=True, max_length=24, unique=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('device', models.CharField(blank=True, max_length=24, null=True)),
                ('primary_device_os', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
