# Generated by Django 2.2.4 on 2019-08-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
