# Generated by Django 2.2.4 on 2019-08-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber', '0002_viberuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='viber_api_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
