# Generated by Django 2.2.4 on 2019-08-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber', '0004_auto_20190823_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
