# Generated by Django 2.2.4 on 2019-08-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber', '0005_viberuser_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viberuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
