# Generated by Django 2.2.4 on 2019-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber', '0006_auto_20190828_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=128, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
